### ISSUE TITLE
--playnext inserts the track into the previous position

### ISSUE THREAD

**Issue by Ansis100** [lwilletts/mpvc#57] opened 2023-10-03 07:43 UTC
**Describe the Issue**
Using --playnext on a track when there is a queued playlist inserts the track into the previous position of the current track.

**To Reproduce**
1. Load a playlist using `mpv --input-ipc-server=/tmp/mpvsocket [playlist link]`
2. Insert a track using `mpvc -A [video link]`
3. If the current track is, e.g. #&#8203;5 in queue, the new track is #&#8203;5 and the currently playing track is #&#8203;6.

**Expected behavior**
The current track stays in the same position and the new track is inserted into the next position.

**Comment by gmt4** [comment] 2023-10-06 12:16
Any missing details to reproduce the issue?, or it can be closed as non-reproducible.

**Comment by Ansis100** [comment] 2023-10-09 07:02
Forgot to mention that the first `mpv` command uses `--input-ipc-server=/tmp/mpvsocket`. Theoretically that should use the same mpv process, right?

**Comment by gmt4** [comment] 2023-10-10 04:26
I can't reproduce the issue after adding the missing mpv option. Can you post the output of `mpvc --version` to confirm you are using the latest mpv version?

**Closed** 2023-11-05 05:35 UTC
Labels: non-reproducible
